name: Build and Push pyIsotonicPEP Image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/pyisopep.yaml'
      - 'pyIsoPEP/*'
      - 'example/*'

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/pyIsotonicPEP
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha,format=long
          labels: |
            org.opencontainers.image.title=pyIsotonicPEP
            org.opencontainers.image.description="Image for estimating Posterior Error Probabilities (PEPs) for identifications using isotonic regression in shotgun proteomics."
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
  
      - name: Build and push pyIsotonicPEP image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./pyIsoPEP/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}