name: Publish pyIsotonicPEP Python Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/PyPIpublish.yml'
      - 'pyIsoPEP/__init__.py'
      - 'pyIsoPEP/main.py'
      - 'pyIsoPEP/IsotonicPEP.py'
      - 'pyproject.toml'
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  # id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip build hatchling
          python -m build

      - name: Build distributions
        run: |
          python -m build --sdist --wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
